// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeBaseStationChannel(arg1, arg2) {
  return window['go']['main']['App']['ChangeBaseStationChannel'](arg1, arg2);
}

export function ChangeBaseStationPowerStatus(arg1, arg2) {
  return window['go']['main']['App']['ChangeBaseStationPowerStatus'](arg1, arg2);
}

export function GetFoundBaseStations() {
  return window['go']['main']['App']['GetFoundBaseStations']();
}

export function IdentitifyBaseStation(arg1) {
  return window['go']['main']['App']['IdentitifyBaseStation'](arg1);
}

export function InitBluetooth() {
  return window['go']['main']['App']['InitBluetooth']();
}

export function IsSteamVRConnected() {
  return window['go']['main']['App']['IsSteamVRConnected']();
}

export function IsSteamVRConnectivityAvailable() {
  return window['go']['main']['App']['IsSteamVRConnectivityAvailable']();
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function SleepAllBaseStations() {
  return window['go']['main']['App']['SleepAllBaseStations']();
}

export function WakeUpAllBaseStations() {
  return window['go']['main']['App']['WakeUpAllBaseStations']();
}
