// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeBaseStationChannel(arg1, arg2) {
  return window['go']['main']['App']['ChangeBaseStationChannel'](arg1, arg2);
}

export function ChangeBaseStationPowerStatus(arg1, arg2) {
  return window['go']['main']['App']['ChangeBaseStationPowerStatus'](arg1, arg2);
}

export function GetFoundBaseStations() {
  return window['go']['main']['App']['GetFoundBaseStations']();
}

export function InitBluetooth() {
  return window['go']['main']['App']['InitBluetooth']();
}
