// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeBaseStationPowerStatus(arg1:string,arg2:string):Promise<string>;

export function GetFoundBaseStations():Promise<Array<main.BaseStation>>;

export function InitBluetooth():Promise<boolean>;
